version: '3'
services:
  web:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=solidtype.net
      - NGINX_PORT=80